name: Django Deployment

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GGH_REGION }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Print Working Directory
      run: pwd
        
    - name: Run tests
      run: python Computex/manage.py test
      
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./Computex
        file: ./Computex/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backendserver:latest
        working-directory: Backend-Frontend

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Terraform Format Check
        working-directory: /Backend-Frontend/Computex
        run: terraform fmt -check
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Verify that the configuration files are syntactically valid
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color

