name: Django Deployment

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Working Directory
        run: pwd

      - name: Run tests
        run: python Computex/manage.py test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./Computex
          file: ./Computex/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backendserver:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set Google Cloud Region
        run: gcloud config set run/region ${{ env.GCP_REGION }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy backend \
            --image ${{ secrets.DOCKER_USERNAME }}/backendserver:latest \
            --project ${{ env.PROJECT_ID }} \
            --platform managed \
            --allow-unauthenticated