name: Django Deployment

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }} # Fixed the typo
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  push_to_registry:
    name: Push frontend image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2 # Updated to the latest version

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4 # Updated to the latest version
      with:
        images: ik3232/ike3232 # Double-check this image name

    - name: Build and push Docker image
      uses: docker/build-push-action@v4 # Updated to the latest version
      with:
        context: ./ComputexFrontend # Path to the directory containing the Dockerfile
        file: ./ComputexFrontend/Dockerfile # Path to the Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}