name: Terraform

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCPREGION }}

jobs:

  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./

    - name: setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT }}
        credentials: ${{ env.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -var="credentials=${{ env.GOOGLE_CREDENTIALS }}"
      working-directory: ./