name: Terraform

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCPREGION }}

jobs:

  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: setup gcloud CLI
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply