name: terraform

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCPREGION }}
  credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Terraform Apply
        if: "contains(github.event.commits[0].message, '[construire]')"
        run: |
          terraform apply -auto-approve

      - name: Terraform Destroy
        if: "contains(github.event.commits[0].message, '[detruire]')"
        run: |
          terraform apply -destroy -auto-approve